development:
  host: localhost
  database: tribune_development

test:
  host: localhost
  database: tribune_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
